[Windows][melodic] Fix ASSIMP libraries path for Windows build
moveit/geometric_shapes pull request #101
Opened 2019-04-01 18:19 UTC by seanyen

This change is another iteration based on #99.

2019-04-01 18:20 UTC, seanyen commented
@rhaschke Sorry I wasn't able to find time to iterate on #99 and here is a version based on your change to make it work on Windows build.

2019-04-01 18:28 UTC, rhaschke requested changes
Looks like I missed to add `PC`. Please try this instead of your addition.

2019-04-01 18:28 UTC, rhaschke commented on CMakeLists.txt
>    find_library(ASSIMP_LIBRARIES assimp HINTS ${ASSIMP_LIBRARY_DIRS})
Please try this instead:
```suggestion
   find_library(ASSIMP_LIBRARIES assimp HINTS ${ASSIMP_PC_LIBRARY_DIRS})
```

2019-04-01 19:59 UTC, seanyen commented
@rhaschke Hi, it turned out on Windows build, `assimp` is discovered by using `CMake` config file so the `pkg-config` code path is not really getting exercised. Anyway, I am pushing a new change which should accommodate both. Let me know what you think.

2019-04-01 20:24 UTC, rhaschke commented
Ok, if Windows detects assimp via a cmake config, what is the actual problem. Shouldn't this work out of the box?

2019-04-01 20:33 UTC, seanyen commented
On Windows build, we are using `assimp` v4.1 (the same like Ubuntu bionic using) and just as many libraries they are producing the CMake config intead of `pkg-config` for Windows build. And from `assimp`, its CMake Config is like this: https://github.com/assimp/assimp/blob/v4.1.0/assimp-config.cmake.in#L42-L51

As you can see, the `${ASSIMP_LIBRARIES}` is defined to be just as the library name like `assimp-vc140-mt` and the library directory is defined in another CMake variable `${ASSIMP_LIBRARY_DIRS}`. However, `${ASSIMP_LIBRARY_DIRS}` was not in the target's link directory, so duing linking stage, it cannot find where the library actually is.

2019-04-02 12:06 UTC, rhaschke requested changes
I added a comment. Otherwise lgtm.

2019-04-02 12:06 UTC, rhaschke commented on CMakeLists.txt
> +# find *absolute* paths to ASSIMP_LIBRARIES
```suggestion
# find *absolute* paths to ASSIMP_LIBRARIES
# Both, pkg-config and assimp's cmake-config don't provide an absolute library path.
# For, pkg-config the path is in ASSIMP_PC_LIBRARY_DIRS, for cmake in ASSIMP_LIBRARY_DIRS.
```

2019-04-02 15:32 UTC, seanyen commented
@rhaschke Thanks. The comments are added.

2019-04-02 17:03 UTC, rhaschke approved these changes

2019-04-02 19:33 UTC, henningkayser approved these changes
Looks good to me!
The kinetic build timed out on Travis so let's wait for the new run to finish.

2019-04-02 19:43 UTC, merged