Added bodies::Body::computeBoundingBox (aligned box version).
moveit/geometric_shapes pull request #104
Opened 2019-05-22 15:27 UTC by peci1

Solves #89 for axis-aligned bounding boxes.

2019-05-22 15:32 UTC, peci1 commented
One thing that needs attention: I needed to make use of class AABB which I originally added about a year ago to moveit::core . But since moveit_core depends on this package and not the other way round, I needed to copy the class' definition.

I think it anyways makes more sense for the AABB class to defined in geometric_shapes. My suggestion on how to tackle code duplication is the following: wait until this PR is merged and new version of geometric_shapes released to public, and then I can send a PR to moveit that will remove the class from there and leave there only a typedef to bodies::AABB for backwards compatibility. So there will be just a short time window where the same class will be defined at two places (in different namespaces, though).

2019-05-25 20:06 UTC, BryceStevenWilley requested changes
Minor nit with the test, but otherwise great!

2019-05-25 20:06 UTC, BryceStevenWilley commented on include/geometric_shapes/aabb.h
> +*   * Neither the name of Willow Garage, Inc. nor the names of its
```suggestion
*   * Neither the name of Open Robotics, nor the names of its
```

2019-05-25 20:06 UTC, BryceStevenWilley commented on test/test_bounding_box.cpp
> +  m.vertices[3 * 0 + 0] = -1;
Factor out the mesh making to a separate function

2019-05-25 20:06 UTC, BryceStevenWilley commented on include/geometric_shapes/aabb.h
> +*   * Neither the name of Willow Garage, Inc. nor the names of its
And elsewhere.

2019-05-25 22:02 UTC, peci1 commented
I did the requested fixes.

2019-05-25 22:25 UTC, BryceStevenWilley commented
Forgot to clang-format, and for some reason, the tests are failing? Can't tell why however.

2019-05-25 22:38 UTC, peci1 commented
Okay, I formatted the code. I also have no idea why the test didn't, run, so let's see if it wasn't just a random glitch.

2019-05-25 23:27 UTC, peci1 commented
Hmm, I still don't see why exactly is the test being not launched. However - do you think it's even correct to test this PR against kinetic-devel if it is only targeted for melodic?

2019-05-28 03:10 UTC, BryceStevenWilley commented
It is strange, but since the melodic branch still builds on kinetic, I don't we want this PR to break that. I've got a kinetic machine that I have access to, I'll try to run that test there and see if I can debug it this week.

2019-05-29 03:40 UTC, peci1 commented
It segfaults in test ` MeshBoundingBox.Mesh1`. This is the stack trace:

```
#0  _int_malloc (av=av@entry=0x7ffffe484b20 <main_arena>, bytes=bytes@entry=352) at malloc.c:3516
#1  0x00007ffffe144184 in __GI___libc_malloc (bytes=352) at malloc.c:2913
#2  0x00007ffffef86b76 in bodies::ConvexMesh::useDimensions(shapes::Shape const*) () from /mnt/d/programovani/ROS/ubuntu16/ws/devel/.private/geometric_shapes/lib/libgeometric_shapes.so
#3  0x00007ffffef81f2a in bodies::Body::setDimensions(shapes::Shape const*) () from /mnt/d/programovani/ROS/ubuntu16/ws/devel/.private/geometric_shapes/lib/libgeometric_shapes.so
#4  0x000000000040fbbd in MeshBoundingBox_Mesh1_Test::TestBody() ()
#5  0x00007fffff1ea823 in void testing::internal::HandleExceptionsInMethodIfSupported<testing::Test, void>(testing::Test*, void (testing::Test::*)(), char const*) ()
   from /mnt/d/Programování/ROS/ubuntu16/ws/build/geometric_shapes/gtest/gtest/libgtest.so
#6  0x00007fffff1dd3ca in testing::Test::Run() () from /mnt/d/Programování/ROS/ubuntu16/ws/build/geometric_shapes/gtest/gtest/libgtest.so
#7  0x00007fffff1dd518 in testing::TestInfo::Run() () from /mnt/d/Programování/ROS/ubuntu16/ws/build/geometric_shapes/gtest/gtest/libgtest.so
#8  0x00007fffff1dd625 in testing::TestCase::Run() () from /mnt/d/Programování/ROS/ubuntu16/ws/build/geometric_shapes/gtest/gtest/libgtest.so
#9  0x00007fffff1e458f in testing::internal::UnitTestImpl::RunAllTests() () from /mnt/d/Programování/ROS/ubuntu16/ws/build/geometric_shapes/gtest/gtest/libgtest.so
#10 0x00007fffff1e48d9 in testing::UnitTest::Run() () from /mnt/d/Programování/ROS/ubuntu16/ws/build/geometric_shapes/gtest/gtest/libgtest.so
#11 0x000000000040548f in main ()
```

I'll keep investigating

2019-05-29 04:12 UTC, peci1 commented
The tests are fixed now.

2019-05-29 18:33 UTC, BryceStevenWilley approved these changes

2019-06-18 13:47 UTC, peci1 commented
Friendly ping. Who could be the 2nd reviewer for this?

2019-06-18 14:17 UTC, v4hn reviewed
looks good to merge to me.

Could you please cleanup the commit history before?

2019-06-18 16:58 UTC, peci1 commented
Done.

2019-07-03 11:33 UTC, v4hn commented
Thanks, sorry, I lost track of this for a while.

2019-07-03 11:33 UTC, merged

2019-08-07 14:14 UTC, peci1 commented
Hi @v4hn , could you please make a new release of geometric_shapes so that this feature is available in the released packages, too?

2019-08-08 06:42 UTC, rhaschke commented
Before preparing a new release of geometric_shapes, we should take care of some other pending PRs.
@ros-planning/moveit-maintainers: Looks like nobody takes care of this repo actively. Please have a look at @peci1's PRs that are open since May...