Throw runtime exception when a shape or body should have a negative dimension.
moveit/geometric_shapes pull request #106
Opened 2019-05-28 16:01 UTC by peci1

Meshes are exceptions - you might want to give it a negative scale to mirror it. Although I'm not sure all member functions would tackle negative scale or large negative padding correctly.

2019-05-28 16:22 UTC, peci1 commented
I was using random() to generate shapes and negative dimensions slipped my attention. What's interesting is they got through the whole pipeline of shape, body, marker and they even displayed in rviz. But the contains/intersectsRay tests are wrong for such bodies.

2019-08-08 07:08 UTC, rhaschke requested changes
I agree that we should check for negative dimensions. In the constructors the checks are fine already.
In the other methods, you should perform the check _before_ modifying the object. Otherwise you leave the object in an undefined state - even if the exception is correctly catched and handled by the caller.

2019-08-08 07:08 UTC, rhaschke commented on src/shapes.cpp
> +  if (radius < 0)
I think the check for valid dimensions should be made before modifying the object.

2019-08-08 09:41 UTC, peci1 commented
I did the requested fixes, please, check if the PR is ready now.

2019-08-08 10:14 UTC, rhaschke reviewed
Code looks good. Please rebase onto melodic-devel. We can't accept merge commits in PRs.

2019-08-09 16:28 UTC, rhaschke approved these changes

2020-03-22 16:38 UTC, peci1 commented
Okay, rebased.

2020-03-22 18:43 UTC, v4hn commented
Merging with second approval.
Thanks @peci1 .

2020-03-22 18:43 UTC, merged